<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">

<HTML>
<HEAD>
	
	<META HTTP-EQUIV="CONTENT-TYPE" CONTENT="text/html; charset=utf-8">
	<TITLE></TITLE>
	<META NAME="GENERATOR" CONTENT="OpenOffice 4.1.2  (Unix)">
	<META NAME="AUTHOR" CONTENT="janeth.ontibon">
	<META NAME="CREATED" CONTENT="20080122;22333200">
	<META NAME="CHANGEDBY" CONTENT="diego vargas">
	<META NAME="CHANGED" CONTENT="20161011;15211000">
	<META NAME="AppVersion" CONTENT="14.0300">
	<META NAME="DocSecurity" CONTENT="0">
	<META NAME="HyperlinksChanged" CONTENT="false">
	<META NAME="LinksUpToDate" CONTENT="false">
	<META NAME="ScaleCrop" CONTENT="false">
	<META NAME="ShareDoc" CONTENT="false">
	
	<STYLE>
		
		
		html {
		  margin: 0;
		}
		body {
		  margin: 1mm 8mm 8mm 2mm;
		}
		@page{
			margin: .75in .7in .75in .7in;
		}

	</STYLE>
	
</HEAD>


<BODY TEXT="#000000">
<TABLE FRAME=VOID ALIGN=LEFT CELLSPACING=0 COLS=23 RULES=NONE BORDER=0>
	<COLGROUP><COL WIDTH=16><COL WIDTH=10><COL WIDTH=119><COL WIDTH=74><COL WIDTH=44><COL WIDTH=87><COL WIDTH=124><COL WIDTH=85><COL WIDTH=45><COL WIDTH=175><COL WIDTH=229><COL WIDTH=75><COL WIDTH=152><COL WIDTH=38><COL WIDTH=41><COL WIDTH=43><COL WIDTH=13><COL WIDTH=56><COL WIDTH=73><COL WIDTH=43><COL WIDTH=84><COL WIDTH=10><COL WIDTH=16></COLGROUP>
	<TBODY>
		<TR>
			<TD WIDTH=16 HEIGHT=14 ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD WIDTH=10 ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD WIDTH=119 ALIGN=LEFT BGCOLOR="#FFFFFF"><FONT SIZE=1><BR></FONT></TD>
			<TD WIDTH=74 ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD WIDTH=44 ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD WIDTH=87 ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD WIDTH=124 ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD WIDTH=85 ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD WIDTH=45 ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD WIDTH=175 ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD WIDTH=229 ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD WIDTH=75 ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD WIDTH=152 ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD WIDTH=38 ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD WIDTH=41 ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD WIDTH=43 ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD WIDTH=13 ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD WIDTH=56 ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD WIDTH=73 ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD WIDTH=43 ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD WIDTH=84 ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD WIDTH=10 ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD WIDTH=16 ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
		</TR>
		<TR>
			<TD HEIGHT=26 ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-top: 3px solid #000000; border-bottom: 3px solid #000000; border-left: 3px solid #000000; border-right: 3px solid #000000" COLSPAN=21 ROWSPAN=3 ALIGN=CENTER VALIGN=MIDDLE BGCOLOR="#FFFFFF"><BR><IMG SRC="{{asset('public/Img/logo_estudio.png')}}" WIDTH=65 HEIGHT=52 HSPACE=466 VSPACE=11>
			</TD>
			<TD ALIGN=LEFT><BR></TD>
		</TR>
		<TR>
			<TD HEIGHT=29 ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
		</TR>
		<TR>
			<TD HEIGHT=17 ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
		</TR>
		<TR>
			<TD HEIGHT=30 ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-left: 3px solid #000000; border-right: 3px solid #000000" COLSPAN=21 ALIGN=CENTER BGCOLOR="#FFFFFF"><B><FONT SIZE=4> ESTUDIO DE CONVENIENCIA Y OPORTUNIDAD</FONT></B></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
		</TR>
		<TR>
			<TD HEIGHT=1 ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-left: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><FONT SIZE=1><BR></FONT></B></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><FONT SIZE=4><BR></FONT></B></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><FONT SIZE=4><BR></FONT></B></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><FONT SIZE=4><BR></FONT></B></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><FONT SIZE=4><BR></FONT></B></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><FONT SIZE=4><BR></FONT></B></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><FONT SIZE=4><BR></FONT></B></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><FONT SIZE=4><BR></FONT></B></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><FONT SIZE=4><BR></FONT></B></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><FONT SIZE=4><BR></FONT></B></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><FONT SIZE=4><BR></FONT></B></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><FONT SIZE=4><BR></FONT></B></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><FONT SIZE=4><BR></FONT></B></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><FONT SIZE=4><BR></FONT></B></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><FONT SIZE=4><BR></FONT></B></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><FONT SIZE=4><BR></FONT></B></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><FONT SIZE=4><BR></FONT></B></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><FONT SIZE=4><BR></FONT></B></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><FONT SIZE=4><BR></FONT></B></TD>
			<TD STYLE="border-right: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
		</TR>
		<TR>
			<TD HEIGHT=20 ALIGN=LEFT BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD STYLE="border-left: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><B><FONT SIZE=1>Bogotá, D.C.  </FONT></B></TD>
			<TD STYLE="border-bottom: 1px solid #333333" COLSPAN=5 ALIGN=CENTER BGCOLOR="#FFFFFF"><B>{{$paas['FechaEstudioConveniencia']}}</B></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD COLSPAN=2 ALIGN=CENTER BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=RIGHT BGCOLOR="#FFFFFF"><B>No.</B>  </TD>
			<TD STYLE="border-bottom: 1px solid #333333" COLSPAN=6 ALIGN=CENTER BGCOLOR="#FFFFFF"><B>{{$paas['Id']}}  -  {{$subdireccion['Iniciales']}}</B></TD>
			<TD STYLE="border-right: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><B><BR></B></TD>
		</TR>
		<TR>
			<TD HEIGHT=5 ALIGN=LEFT BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD STYLE="border-left: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><B><FONT SIZE=1><BR></FONT></B></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=RIGHT BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=RIGHT BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=RIGHT BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD STYLE="border-right: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><B><BR></B></TD>
		</TR>
		<TR>
			<TD HEIGHT=38 ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-left: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-top: 1px solid #333333; border-bottom: 1px solid #333333; border-left: 1px solid #333333; border-right: 1px solid #333333" COLSPAN=7 ALIGN=CENTER VALIGN=MIDDLE BGCOLOR="#C0C0C0"><B><FONT SIZE=3>DEPENDENCIA SOLICITANTE   (Seleccione de la lista) </FONT></B></TD>
			<TD STYLE="border-top: 1px solid #333333; border-bottom: 1px solid #333333; border-left: 1px solid #333333; border-right: 1px solid #333333" COLSPAN=12 ALIGN=CENTER VALIGN=MIDDLE BGCOLOR="#FFFFFF"><B><FONT SIZE=3>SUBDIRECCIÓN ADMINISTRATIVA Y FINANCIERA</FONT></B></TD>
			<TD STYLE="border-right: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
		</TR>
		<TR>
			<TD HEIGHT=9 ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-left: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><FONT SIZE=1><BR></FONT></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><FONT SIZE=1><BR></FONT></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><FONT SIZE=1><BR></FONT></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><FONT SIZE=1><BR></FONT></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-right: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
		</TR>
		<TR>
			<TD HEIGHT=40 ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-left: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-top: 1px solid #333333; border-bottom: 1px solid #333333; border-left: 1px solid #333333; border-right: 1px solid #333333" COLSPAN=3 ALIGN=CENTER VALIGN=MIDDLE BGCOLOR="#969696"><B><FONT SIZE=3>TIPO DE CONTRATO   (Seleccione de la lista) </FONT></B></TD>
			<TD STYLE="border-top: 1px solid #333333; border-bottom: 1px solid #333333; border-left: 1px solid #333333; border-right: 1px solid #333333" COLSPAN=8 ALIGN=CENTER VALIGN=MIDDLE BGCOLOR="#FFFFFF"><FONT SIZE=3>{{$paas->tipocontrato['Nombre']}}</FONT></TD>
			<TD STYLE="border-top: 1px solid #333333; border-bottom: 1px solid #333333; border-left: 1px solid #333333; border-right: 1px solid #333333" ALIGN=LEFT VALIGN=MIDDLE BGCOLOR="#969696"><B><FONT SIZE=3><BR></FONT></B></TD>
			<TD STYLE="border-top: 1px solid #333333; border-bottom: 1px solid #333333; border-left: 1px solid #333333; border-right: 1px solid #333333" COLSPAN=5 ALIGN=CENTER VALIGN=MIDDLE BGCOLOR="#969696"><B><FONT SIZE=3>RECURSO HUMANO   (Seleccione de la lista) </FONT></B></TD>
			<TD STYLE="border-top: 1px solid #333333; border-bottom: 1px solid #333333; border-left: 1px solid #333333; border-right: 1px solid #333333" COLSPAN=2 ALIGN=CENTER VALIGN=MIDDLE BGCOLOR="#FFFFFF"><FONT SIZE=3>{{$paas['RecursoHumano']}}</FONT></TD>
			<TD STYLE="border-right: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
		</TR>
		<TR>
			<TD HEIGHT=6 ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-left: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=CENTER VALIGN=MIDDLE BGCOLOR="#FFFFFF"><B><FONT SIZE=1><BR></FONT></B></TD>
			<TD ALIGN=CENTER VALIGN=MIDDLE BGCOLOR="#FFFFFF"><B><FONT SIZE=3><BR></FONT></B></TD>
			<TD ALIGN=CENTER VALIGN=MIDDLE BGCOLOR="#FFFFFF"><FONT SIZE=3><BR></FONT></TD>
			<TD ALIGN=CENTER VALIGN=MIDDLE BGCOLOR="#FFFFFF"><FONT SIZE=3><BR></FONT></TD>
			<TD ALIGN=CENTER VALIGN=MIDDLE BGCOLOR="#FFFFFF"><FONT SIZE=3><BR></FONT></TD>
			<TD ALIGN=CENTER VALIGN=MIDDLE BGCOLOR="#FFFFFF"><FONT SIZE=3><BR></FONT></TD>
			<TD ALIGN=CENTER VALIGN=MIDDLE BGCOLOR="#FFFFFF"><FONT SIZE=3><BR></FONT></TD>
			<TD ALIGN=CENTER VALIGN=MIDDLE BGCOLOR="#FFFFFF"><FONT SIZE=3><BR></FONT></TD>
			<TD ALIGN=CENTER VALIGN=MIDDLE BGCOLOR="#FFFFFF"><FONT SIZE=3><BR></FONT></TD>
			<TD ALIGN=CENTER VALIGN=MIDDLE BGCOLOR="#FFFFFF"><FONT SIZE=3><BR></FONT></TD>
			<TD ALIGN=CENTER VALIGN=MIDDLE BGCOLOR="#FFFFFF"><FONT SIZE=3><BR></FONT></TD>
			<TD ALIGN=CENTER VALIGN=MIDDLE BGCOLOR="#FFFFFF"><FONT SIZE=3><BR></FONT></TD>
			<TD ALIGN=CENTER VALIGN=MIDDLE BGCOLOR="#FFFFFF"><FONT SIZE=3><BR></FONT></TD>
			<TD ALIGN=CENTER VALIGN=MIDDLE BGCOLOR="#FFFFFF"><FONT SIZE=3><BR></FONT></TD>
			<TD ALIGN=CENTER VALIGN=MIDDLE BGCOLOR="#FFFFFF"><FONT SIZE=3><BR></FONT></TD>
			<TD ALIGN=CENTER VALIGN=MIDDLE BGCOLOR="#FFFFFF"><FONT SIZE=3><BR></FONT></TD>
			<TD ALIGN=CENTER VALIGN=MIDDLE BGCOLOR="#FFFFFF"><FONT SIZE=3><BR></FONT></TD>
			<TD ALIGN=CENTER VALIGN=MIDDLE BGCOLOR="#FFFFFF"><FONT SIZE=3><BR></FONT></TD>
			<TD ALIGN=CENTER VALIGN=MIDDLE BGCOLOR="#FFFFFF"><FONT SIZE=3><BR></FONT></TD>
			<TD STYLE="border-right: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
		</TR>
		<TR>
			<TD HEIGHT=7 ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-left: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><FONT SIZE=1><BR></FONT></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><FONT SIZE=1><BR></FONT></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><FONT SIZE=1><BR></FONT></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><FONT SIZE=1><BR></FONT></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-right: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
		</TR>
		<TR>
			<TD HEIGHT=31 ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-left: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-top: 1px solid #333333; border-bottom: 1px solid #333333; border-left: 1px solid #333333; border-right: 1px solid #333333" COLSPAN=19 ALIGN=CENTER VALIGN=MIDDLE BGCOLOR="#C0C0C0"><B><FONT SIZE=6>OBJETO CONTRATO</FONT></B></TD>
			<TD STYLE="border-right: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
		</TR>
		<TR>
			<TD HEIGHT=62 ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-left: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-top: 1px solid #333333; vertical-align: top; border-bottom: 1px solid #333333; border-left: 1px solid #333333; border-right: 1px solid #333333; font-family: Arial, Helvetica, Verdana; padding-left: 5px; padding-right: 5px;" COLSPAN=19 ALIGN=JUSTIFY VALIGN=MIDDLE BGCOLOR="#FFFFFF"><FONT SIZE=5>{{$paas['ObjetoContractual']}}</FONT></TD>
			<TD STYLE="border-right: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
		</TR>
		<TR>
			<TD HEIGHT=12 ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-left: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><FONT SIZE=1><BR></FONT></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><FONT SIZE=1><BR></FONT></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><FONT SIZE=1><BR></FONT></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><FONT SIZE=1><BR></FONT></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><FONT SIZE=1><BR></FONT></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><FONT SIZE=1><BR></FONT></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><FONT SIZE=1><BR></FONT></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><FONT SIZE=1><BR></FONT></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><FONT SIZE=1><BR></FONT></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><FONT SIZE=1><BR></FONT></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><FONT SIZE=1><BR></FONT></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><FONT SIZE=1><BR></FONT></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><FONT SIZE=1><BR></FONT></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><FONT SIZE=1><BR></FONT></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><FONT SIZE=1><BR></FONT></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><FONT SIZE=1><BR></FONT></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><FONT SIZE=1><BR></FONT></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><FONT SIZE=1><BR></FONT></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><FONT SIZE=1><BR></FONT></TD>
			<TD STYLE="border-right: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
		</TR>
		<TR>
			<TD HEIGHT=26 ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-left: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" COLSPAN=19 ALIGN=CENTER VALIGN=MIDDLE BGCOLOR="#C0C0C0"><B><FONT SIZE=6>CONVENIENCIA</FONT></B></TD>
			<TD STYLE="border-right: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
		</TR>
		<TR>
			<TD HEIGHT=11 ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-left: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><FONT SIZE=1><BR></FONT></B></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD STYLE="border-right: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
		</TR>
		<TR>
			<TD HEIGHT=26 ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-left: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; vertical-align: top; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000; font-family: Arial, Helvetica, Verdana; padding-left: 5px; padding-right: 5px;" COLSPAN=19 ROWSPAN=5 ALIGN=JUSTIFY VALIGN=MIDDLE BGCOLOR="#FFFFFF" ><FONT SIZE=5 COLOR="#000000">
			@if (!empty($EstudioConveniencias['conveniencia']))
				{{$EstudioConveniencias['conveniencia']}}
			@endif
			<BR></FONT></TD>
			<TD STYLE="border-right: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
		</TR>
		<TR>
			<TD HEIGHT=26 ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-left: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-right: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
		</TR>
		<TR>
			<TD HEIGHT=26 ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-left: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-right: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
		</TR>
		<TR>
			<TD HEIGHT=22 ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-left: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-right: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
		</TR>
		<TR>
			<TD HEIGHT=33 ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-left: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-right: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
		</TR>

		<TR>
			<TD HEIGHT=11 ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-left: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><FONT SIZE=1><BR></FONT></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-right: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
		</TR>
		<TR>
			<TD HEIGHT=28 ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-left: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" COLSPAN=19 ALIGN=CENTER VALIGN=MIDDLE BGCOLOR="#C0C0C0"><B><FONT SIZE=6>OPORTUNIDAD</FONT></B></TD>
			<TD STYLE="border-right: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
		</TR>
		<TR>
			<TD HEIGHT=11 ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-left: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><FONT SIZE=1><BR></FONT></B></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD STYLE="border-right: 3px solid #000000" ALIGN=LEFT><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
		</TR>
		<TR>
			<TD HEIGHT=26 ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-left: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; vertical-align: top; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000; font-family: Arial, Helvetica, Verdana; padding-left: 5px; padding-right: 5px;" COLSPAN=19 ROWSPAN=3 ALIGN=JUSTIFY VALIGN=MIDDLE><FONT SIZE=5 COLOR="#000000">
			@if (!empty($EstudioConveniencias['oportunidad']))
				{{$EstudioConveniencias['oportunidad']}}
			@endif
			<BR></FONT></TD>
			<TD STYLE="border-right: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
		</TR>
		<TR>
			<TD HEIGHT=168 ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-left: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-right: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
		</TR>
		<TR>
			<TD HEIGHT=64 ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-left: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-right: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
		</TR>
		<TR>
			<TD HEIGHT=11 ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-left: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><FONT SIZE=1><BR></FONT></B></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD STYLE="border-right: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
		</TR>
		<TR>
			<TD HEIGHT=29 ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-left: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000; padding-left: 5px; padding-right: 5px;" COLSPAN=19 ALIGN=CENTER VALIGN=MIDDLE BGCOLOR="#C0C0C0"><B><FONT SIZE=6>JUSTIFICACIÓN</FONT></B></TD>
			<TD STYLE="border-right: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
		</TR>
		<TR>
			<TD HEIGHT=11 ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-left: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><FONT SIZE=1><BR></FONT></B></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD STYLE="border-right: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
		</TR>
		<TR>
			<TD HEIGHT=26 ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-left: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; vertical-align: top; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000; font-family: Arial, Helvetica, Verdana; padding-left: 5px; padding-right: 5px;" COLSPAN=19 ROWSPAN=5 ALIGN=JUSTIFY VALIGN=MIDDLE BGCOLOR="#FFFFFF"><FONT SIZE=5 COLOR="#000000">@if (!empty($EstudioConveniencias['justificacion']))
				{{$EstudioConveniencias['justificacion']}}
			@endif
			<BR></FONT></TD>
			<TD STYLE="border-right: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
		</TR>
		<TR>
			<TD HEIGHT=12 ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-left: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-right: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
		</TR>
		<TR>
			<TD HEIGHT=32 ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-left: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-right: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
		</TR>
		<TR>
			<TD HEIGHT=26 ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-left: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-right: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
		</TR>
		<TR>
			<TD HEIGHT=26 ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-left: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-right: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
		</TR>
		<TR>
			<TD HEIGHT=10 ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-left: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT VALIGN=MIDDLE BGCOLOR="#FFFFFF"><B><FONT SIZE=1><BR></FONT></B></TD>
			<TD ALIGN=LEFT VALIGN=MIDDLE BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=LEFT VALIGN=MIDDLE BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=LEFT VALIGN=MIDDLE BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=LEFT VALIGN=MIDDLE BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT VALIGN=MIDDLE BGCOLOR="#FFFFFF"><B><FONT SIZE=3><BR></FONT></B></TD>
			<TD ALIGN=LEFT VALIGN=MIDDLE BGCOLOR="#FFFFFF"><B><FONT SIZE=3><BR></FONT></B></TD>
			<TD ALIGN=LEFT VALIGN=MIDDLE BGCOLOR="#FFFFFF"><B><FONT SIZE=3><BR></FONT></B></TD>
			<TD ALIGN=LEFT VALIGN=MIDDLE BGCOLOR="#FFFFFF"><B><FONT SIZE=3><BR></FONT></B></TD>
			<TD ALIGN=LEFT VALIGN=MIDDLE BGCOLOR="#FFFFFF"><B><FONT SIZE=3><BR></FONT></B></TD>
			<TD ALIGN=LEFT VALIGN=MIDDLE BGCOLOR="#FFFFFF"><B><FONT SIZE=3><BR></FONT></B></TD>
			<TD ALIGN=LEFT VALIGN=MIDDLE BGCOLOR="#FFFFFF"><B><FONT SIZE=3><BR></FONT></B></TD>
			<TD ALIGN=LEFT VALIGN=MIDDLE BGCOLOR="#FFFFFF"><B><FONT SIZE=3><BR></FONT></B></TD>
			<TD ALIGN=LEFT VALIGN=MIDDLE BGCOLOR="#FFFFFF"><B><FONT SIZE=3><BR></FONT></B></TD>
			<TD ALIGN=LEFT VALIGN=MIDDLE BGCOLOR="#FFFFFF"><B><FONT SIZE=3><BR></FONT></B></TD>
			<TD ALIGN=LEFT VALIGN=MIDDLE BGCOLOR="#FFFFFF"><B><FONT SIZE=3><BR></FONT></B></TD>
			<TD ALIGN=LEFT VALIGN=MIDDLE BGCOLOR="#FFFFFF"><B><FONT SIZE=3><BR></FONT></B></TD>
			<TD ALIGN=LEFT VALIGN=MIDDLE BGCOLOR="#FFFFFF"><B><FONT SIZE=3><BR></FONT></B></TD>
			<TD ALIGN=LEFT VALIGN=MIDDLE BGCOLOR="#FFFFFF"><B><FONT SIZE=3><BR></FONT></B></TD>
			<TD STYLE="border-right: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
		</TR>
		<TR>
			<TD HEIGHT=36 ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-left: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-top: 1px solid #333333; border-bottom: 1px solid #333333; border-left: 1px solid #333333; border-right: 1px solid #333333" COLSPAN=4 ALIGN=CENTER VALIGN=MIDDLE BGCOLOR="#969696"><B><FONT SIZE=3>PLAZO DE EJECUCIÓN  </FONT></B></TD>
			<TD STYLE="border-top: 1px solid #333333; border-bottom: 1px solid #333333; border-left: 1px solid #333333; border-right: 1px solid #333333" COLSPAN=15 ALIGN=CENTER VALIGN=MIDDLE BGCOLOR="#FFFFFF"><B>{{$paas['DuracionContrato']}} </B></TD>
			<TD STYLE="border-right: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
		</TR>
		<TR>
			<TD HEIGHT=17 ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-left: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT VALIGN=MIDDLE BGCOLOR="#FFFFFF"><B><FONT SIZE=1><BR></FONT></B></TD>
			<TD ALIGN=LEFT VALIGN=MIDDLE BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=LEFT VALIGN=MIDDLE BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=LEFT VALIGN=MIDDLE BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=LEFT VALIGN=MIDDLE BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT VALIGN=MIDDLE BGCOLOR="#FFFFFF"><B><FONT SIZE=3><BR></FONT></B></TD>
			<TD ALIGN=LEFT VALIGN=MIDDLE BGCOLOR="#FFFFFF"><B><FONT SIZE=3><BR></FONT></B></TD>
			<TD ALIGN=LEFT VALIGN=MIDDLE BGCOLOR="#FFFFFF"><B><FONT SIZE=3><BR></FONT></B></TD>
			<TD ALIGN=LEFT VALIGN=MIDDLE BGCOLOR="#FFFFFF"><B><FONT SIZE=3><BR></FONT></B></TD>
			<TD ALIGN=LEFT VALIGN=MIDDLE BGCOLOR="#FFFFFF"><B><FONT SIZE=3><BR></FONT></B></TD>
			<TD ALIGN=LEFT VALIGN=MIDDLE BGCOLOR="#FFFFFF"><B><FONT SIZE=3><BR></FONT></B></TD>
			<TD ALIGN=LEFT VALIGN=MIDDLE BGCOLOR="#FFFFFF"><B><FONT SIZE=3><BR></FONT></B></TD>
			<TD ALIGN=LEFT VALIGN=MIDDLE BGCOLOR="#FFFFFF"><B><FONT SIZE=3><BR></FONT></B></TD>
			<TD ALIGN=LEFT VALIGN=MIDDLE BGCOLOR="#FFFFFF"><B><FONT SIZE=3><BR></FONT></B></TD>
			<TD ALIGN=LEFT VALIGN=MIDDLE BGCOLOR="#FFFFFF"><B><FONT SIZE=3><BR></FONT></B></TD>
			<TD ALIGN=LEFT VALIGN=MIDDLE BGCOLOR="#FFFFFF"><B><FONT SIZE=3><BR></FONT></B></TD>
			<TD ALIGN=LEFT VALIGN=MIDDLE BGCOLOR="#FFFFFF"><B><FONT SIZE=3><BR></FONT></B></TD>
			<TD ALIGN=LEFT VALIGN=MIDDLE BGCOLOR="#FFFFFF"><B><FONT SIZE=3><BR></FONT></B></TD>
			<TD ALIGN=LEFT VALIGN=MIDDLE BGCOLOR="#FFFFFF"><B><FONT SIZE=3><BR></FONT></B></TD>
			<TD STYLE="border-right: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
		</TR>
		<TR>
			<TD HEIGHT=8 ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-left: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT VALIGN=MIDDLE BGCOLOR="#FFFFFF"><B><FONT SIZE=1><BR></FONT></B></TD>
			<TD ALIGN=LEFT VALIGN=MIDDLE BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=LEFT VALIGN=MIDDLE BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=LEFT VALIGN=MIDDLE BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=LEFT VALIGN=MIDDLE BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT VALIGN=MIDDLE BGCOLOR="#FFFFFF"><B><FONT SIZE=3><BR></FONT></B></TD>
			<TD ALIGN=LEFT VALIGN=MIDDLE BGCOLOR="#FFFFFF"><B><FONT SIZE=3><BR></FONT></B></TD>
			<TD ALIGN=LEFT VALIGN=MIDDLE BGCOLOR="#FFFFFF"><B><FONT SIZE=3><BR></FONT></B></TD>
			<TD ALIGN=LEFT VALIGN=MIDDLE BGCOLOR="#FFFFFF"><B><FONT SIZE=3><BR></FONT></B></TD>
			<TD ALIGN=LEFT VALIGN=MIDDLE BGCOLOR="#FFFFFF"><B><FONT SIZE=3><BR></FONT></B></TD>
			<TD ALIGN=LEFT VALIGN=MIDDLE BGCOLOR="#FFFFFF"><B><FONT SIZE=3><BR></FONT></B></TD>
			<TD ALIGN=LEFT VALIGN=MIDDLE BGCOLOR="#FFFFFF"><B><FONT SIZE=3><BR></FONT></B></TD>
			<TD ALIGN=LEFT VALIGN=MIDDLE BGCOLOR="#FFFFFF"><B><FONT SIZE=3><BR></FONT></B></TD>
			<TD ALIGN=LEFT VALIGN=MIDDLE BGCOLOR="#FFFFFF"><B><FONT SIZE=3><BR></FONT></B></TD>
			<TD ALIGN=LEFT VALIGN=MIDDLE BGCOLOR="#FFFFFF"><B><FONT SIZE=3><BR></FONT></B></TD>
			<TD ALIGN=LEFT VALIGN=MIDDLE BGCOLOR="#FFFFFF"><B><FONT SIZE=3><BR></FONT></B></TD>
			<TD ALIGN=LEFT VALIGN=MIDDLE BGCOLOR="#FFFFFF"><B><FONT SIZE=3><BR></FONT></B></TD>
			<TD ALIGN=LEFT VALIGN=MIDDLE BGCOLOR="#FFFFFF"><B><FONT SIZE=3><BR></FONT></B></TD>
			<TD ALIGN=LEFT VALIGN=MIDDLE BGCOLOR="#FFFFFF"><B><FONT SIZE=3><BR></FONT></B></TD>
			<TD STYLE="border-right: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
		</TR>
		<TR>
			<TD HEIGHT=26 ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			
			<TD STYLE="border-left: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			
			<TD STYLE="border-top: 1px solid #333333; border-bottom: 1px solid #333333; border-left: 1px solid #333333; border-right: 1px solid #333333" COLSPAN=2 ROWSPAN=2 ALIGN=CENTER VALIGN=MIDDLE BGCOLOR="#969696"><B><FONT SIZE=3>COD. Y NOMBRE DEL RUBRO O PROYECTO <BR>  (Seleccione de la lista) </FONT></B></TD>

			<TD STYLE="border-top: 1px solid #333333; border-left: 1px solid #333333; border-right: 1px solid #333333" COLSPAN=2 ROWSPAN=2 ALIGN=CENTER VALIGN=MIDDLE BGCOLOR="#969696"><B><FONT SIZE=3>META </FONT></B></TD>
			
			<TD STYLE="border-top: 1px solid #333333; border-left: 1px solid #333333; border-right: 1px solid #333333" COLSPAN=3 ROWSPAN=2 ALIGN=CENTER VALIGN=MIDDLE BGCOLOR="#969696"><B><FONT SIZE=3>NOMBRE Y PORCENTAJE DE LA ACTIVIDAD  DEL PROYECTO  QUE SE AFECTA (diligencie) </FONT></B></TD>
			
			<TD STYLE="border-top: 1px solid #333333; border-left: 1px solid #333333; border-right: 1px solid #333333"  ROWSPAN=2 ALIGN=CENTER VALIGN=MIDDLE BGCOLOR="#969696" COLSPAN=3><B><FONT SIZE=3>CLASIFICACIÓN DEL GASTO DE INVERSIÓN   <BR> (Seleccione de la lista) </FONT></B></TD>
			
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #333333; border-right: 1px solid #000000" COLSPAN=7 ALIGN=CENTER VALIGN=MIDDLE BGCOLOR="#969696"><B><FONT SIZE=3>CLASIFICACIÓN DE LAS FUENTES DE FINANCIACIÓN</FONT></B></TD>
			
			<TD STYLE="border-top: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000; " COLSPAN=2 ROWSPAN=2 ALIGN=CENTER VALIGN=MIDDLE BGCOLOR="#969696"><B><FONT SIZE=3>VALOR</FONT></B></TD>
			
			<TD STYLE="border-right: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
		</TR>
		<TR>
			<TD HEIGHT=64 ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-left: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			
			
			<TD STYLE="border-top: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" COLSPAN=2 ALIGN=CENTER VALIGN=MIDDLE BGCOLOR="#969696"><B><FONT SIZE=3>DETALLE FUENTE - HACIENDA<BR> (Seleccione de la lista) </FONT></B></TD>
			<TD STYLE="border-top: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" COLSPAN=5 ALIGN=CENTER VALIGN=MIDDLE BGCOLOR="#969696"><B><FONT SIZE=3>DETALLE FUENTE - IDRD <BR> (Seleccione de la lista) </FONT></B></TD>
			
			<TD STYLE="border-right: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT><BR></TD>
		</TR>
		<?php /**/ $var = 0; ?>
		@foreach($finanzas as $finanza)
			@foreach($finanza->actividades as &$actividad)
			<TR>
			<TD HEIGHT=auto ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-left: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			
			<TD STYLE="border-top: 1px solid #333333; border-bottom: 1px solid #333333; border-left: 1px solid #333333; border-right: 1px solid #333333; padding-left: 5px; " COLSPAN=2 VALIGN=MIDDLE BGCOLOR="#FFFFFF"><FONT SIZE=5 COLOR="#000000">{{$paas->proyecto['codigo']}} - {{$paas->proyecto['Nombre']}}</FONT></TD>

			<TD STYLE="border-top: 1px solid #333333; border-bottom: 1px solid #333333; border-left: 1px solid #333333; border-right: 1px solid #333333; padding-left: 5px;" COLSPAN=2 ALIGN=LEFT VALIGN=MIDDLE BGCOLOR="#FFFFFF"><FONT SIZE=5 COLOR="#000000">{{$actividad->Actividad->meta['Nombre']}}</FONT></TD>	
			
			<TD STYLE="border-top: 1px solid #333333; border-bottom: 1px solid #333333; border-left: 1px solid #333333; border-right: 1px solid #333333; padding-left: 5px;" COLSPAN=3 ALIGN=LEFT VALIGN=MIDDLE BGCOLOR="#FFFFFF">
			<FONT SIZE=5 COLOR="#000000">{{$actividad->Actividad['Nombre']}} - {{$actividad->pivot['porcentaje']}}%</FONT>
			</TD>

			<TD STYLE="border-top: 1px solid #333333; border-bottom: 1px solid #333333; border-left: 1px solid #333333; border-right: 1px solid #333333; padding-left: 5px;"  COLSPAN=3 ALIGN=LEFT VALIGN=MIDDLE BGCOLOR="#FFFFFF"><FONT SIZE=5 COLOR="#000000">{{$finanza->Componente['Nombre']}}</FONT></TD>

			<TD STYLE="border-top: 1px solid #333333; border-bottom: 1px solid #333333; border-left: 1px solid #333333; border-right: 1px solid #333333; padding-left: 5px;" COLSPAN=2 ALIGN=LEFT VALIGN=MIDDLE BGCOLOR="#FFFFFF"><FONT SIZE=5 COLOR="#000000">{{$actividad->Fuente['nombre']}}</FONT></TD>


			<TD STYLE="border-top: 1px solid #333333; border-bottom: 1px solid #333333; border-left: 1px solid #333333; border-right: 1px solid #333333; padding-left: 5px;" COLSPAN=5 ALIGN=LEFT VALIGN=MIDDLE BGCOLOR="#FFFFFF"><FONT SIZE=5 COLOR="#000000">{{$finanza->componente->fuente['nombre']}}</FONT></TD>

			<TD STYLE="border-top: 1px solid #333333; border-bottom: 1px solid #333333; border-left: 1px solid #333333; border-right: 1px solid #333333; padding-left: 5px;" COLSPAN=2 ALIGN=LEFT VALIGN=MIDDLE BGCOLOR="#FFFFFF" SDNUM="2058;0;[$$-240A] #,##0"><FONT SIZE=4 COLOR="#000000">${{$actividad->pivot['valor']}}</FONT></TD>

			<?php /**/ $var = $var+$actividad->pivot['valor'] /**/ ?>
			<TD STYLE="border-right: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"></TD>

			<TD ALIGN=LEFT></TD>
			</TR>
			@endforeach
		@endforeach

			<TR>
				<TD HEIGHT=auto ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
				<TD STYLE="border-left: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
				
				<TD STYLE="border-top: 1px solid #333333; border-bottom: 1px solid #333333; border-left: 1px solid #333333; border-right: 1px solid #333333; padding-left: 5px; " COLSPAN=2 VALIGN=MIDDLE BGCOLOR="#FFFFFF"><FONT SIZE=5>TOTAL</FONT></TD>

				<TD STYLE="border-top: 1px solid #333333; border-bottom: 1px solid #333333; border-left: 1px solid #333333; border-right: 1px solid #333333; padding-left: 5px;" COLSPAN=15 ALIGN=LEFT VALIGN=MIDDLE BGCOLOR="#FFFFFF"></TD>

				<TD STYLE="border-top: 1px solid #333333; border-bottom: 1px solid #333333; border-left: 1px solid #333333; border-right: 1px solid #333333; padding-left: 5px;" COLSPAN=2 ALIGN=LEFT VALIGN=MIDDLE BGCOLOR="#FFFFFF" SDNUM="2058;0;[$$-240A] #,##0"><FONT SIZE=5 COLOR="#000000">${{$var}}</FONT></TD>

				<TD STYLE="border-right: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"></TD>

				<TD ALIGN=LEFT></TD>
			</TR>

		<TR>
			<TD HEIGHT=16 ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-left: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><B><FONT SIZE=1><BR></FONT></B></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD STYLE="border-right: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
		</TR>
		<TR>
			<TD HEIGHT=26 ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-left: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD COLSPAN=19 ALIGN=CENTER VALIGN=MIDDLE BGCOLOR="#FFFFFF"><FONT SIZE=3>Certifico que las fuentes  de financiación asignadas en este estudio de conveniencia  para financiar el objeto contractual a realizarse, están de acuerdo con las normas vigentes aplicables</FONT></TD>
			<TD STYLE="border-right: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
		</TR>
		<TR>
			<TD HEIGHT=129 ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-left: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT VALIGN=MIDDLE BGCOLOR="#FFFFFF"><FONT SIZE=1><BR></FONT></TD>
			<TD  COLSPAN=3 ALIGN=CENTER VALIGN=MIDDLE BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT VALIGN=MIDDLE BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-bottom: 5px solid #000000" ALIGN=LEFT VALIGN=MIDDLE BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-bottom: 5px solid #000000" ALIGN=LEFT VALIGN=MIDDLE BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-bottom: 5px solid #000000" ALIGN=LEFT VALIGN=MIDDLE BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-bottom: 5px solid #000000" ALIGN=CENTER VALIGN=MIDDLE BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-bottom: 5px solid #000000" ALIGN=CENTER VALIGN=MIDDLE BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-bottom: 5px solid #000000" ALIGN=CENTER VALIGN=MIDDLE BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=CENTER VALIGN=MIDDLE BGCOLOR="#FFFFFF"><BR></TD>
			<TD  COLSPAN=6 ALIGN=CENTER VALIGN=MIDDLE BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT VALIGN=MIDDLE BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-right: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
		</TR>
		<TR>
			<TD HEIGHT=32 ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-left: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT VALIGN=MIDDLE BGCOLOR="#FFFFFF"><FONT SIZE=1><BR></FONT></TD>
			<TD COLSPAN=16 ALIGN=CENTER VALIGN=MIDDLE BGCOLOR="#FFFFFF"><B><FONT SIZE=3>{{$subdireccion['SubDireccion']}}  -  {{$subdireccion['Descripcion']}}</FONT></B></TD>
			<TD ALIGN=LEFT><BR></TD>
			<TD ALIGN=LEFT VALIGN=MIDDLE BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-right: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
		</TR>
		<TR>
			<TD HEIGHT=25 ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-left: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD COLSPAN=16 ALIGN=CENTER VALIGN=MIDDLE BGCOLOR="#FFFFFF"><B>{{$subdireccion['nombre']}}</B></TD>
			<TD ALIGN=LEFT><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-right: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
		</TR>
		<TR>
			<TD HEIGHT=12 ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-left: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><FONT SIZE=1><BR></FONT></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=CENTER VALIGN=TOP BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=CENTER VALIGN=TOP BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=CENTER VALIGN=TOP BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=CENTER VALIGN=TOP BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=CENTER VALIGN=TOP BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=CENTER VALIGN=TOP BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=CENTER VALIGN=TOP BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=CENTER VALIGN=TOP BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=CENTER VALIGN=TOP BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=CENTER VALIGN=TOP BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=CENTER VALIGN=TOP BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-right: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
		</TR>
		<TR>
			<TD HEIGHT=26 ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-top: 3px solid #333333; border-bottom: 3px solid #333333; border-left: 3px solid #333333; border-right: 3px solid #333333" COLSPAN=21 ALIGN=CENTER VALIGN=MIDDLE BGCOLOR="#969696"><B><FONT SIZE=3>ESPACIO PARA SER DILIGENCIADO POR LA OFICINA ASESORA DE PLANEACIÓN</FONT></B></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
		</TR>
		<TR>
			<TD HEIGHT=28 ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-top: 3px solid #333333; border-left: 3px solid #333333" ALIGN=CENTER VALIGN=MIDDLE BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=CENTER VALIGN=MIDDLE BGCOLOR="#FFFFFF"><B><FONT SIZE=1><BR></FONT></B></TD>
			<TD ALIGN=CENTER VALIGN=MIDDLE BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=CENTER VALIGN=MIDDLE BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=CENTER VALIGN=MIDDLE BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=CENTER VALIGN=MIDDLE BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=CENTER VALIGN=MIDDLE BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=CENTER VALIGN=MIDDLE BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=CENTER VALIGN=MIDDLE BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=CENTER VALIGN=MIDDLE BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD STYLE="border-top: 3px solid #333333" COLSPAN=7 ROWSPAN=3 ALIGN=CENTER BGCOLOR="#FFFFFF">La viabilidad  expedida  por la Oficina Asesora de Planeación se refiere a la coherencia  del objeto contractual con la formulación del proyecto de inversión, la ficha EBI y el Plan Anual de Adquisiciones del IDRD</TD>
			<TD ALIGN=CENTER VALIGN=MIDDLE BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=CENTER VALIGN=MIDDLE BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=CENTER VALIGN=MIDDLE BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=CENTER VALIGN=MIDDLE BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD STYLE="border-left: 3px solid #333333" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
		</TR>
		<TR>
			<TD HEIGHT=26 ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-left: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><FONT SIZE=1><BR></FONT></TD>
			<TD ALIGN=RIGHT BGCOLOR="#FFFFFF"><FONT SIZE=3>APROBADO </FONT></TD>
			<TD STYLE="border-top: 1px solid #333333; border-bottom: 1px solid #333333; border-left: 1px solid #333333; border-right: 1px solid #333333" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><FONT SIZE=3>DEVUELTO </FONT></TD>
			<TD ALIGN=LEFT><BR></TD>
			<TD STYLE="border-top: 1px solid #333333; border-bottom: 1px solid #333333; border-left: 1px solid #333333; border-right: 1px solid #333333" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-right: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
		</TR>
		<TR>
			<TD HEIGHT=19 ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-left: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><FONT SIZE=1><BR></FONT></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-right: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
		</TR>
		<TR>
			<TD HEIGHT=75 ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-left: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD COLSPAN=2 ALIGN=RIGHT VALIGN=MIDDLE BGCOLOR="#FFFFFF"><FONT SIZE=3>FECHA DE INGRESO </FONT></TD>
			<TD STYLE="border-bottom: 3px solid #333333" COLSPAN=5 ALIGN=CENTER VALIGN=MIDDLE BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=RIGHT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=RIGHT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-bottom: 5px solid #000000" COLSPAN=7 ALIGN=CENTER BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-right: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
		</TR>
		<TR>
			<TD HEIGHT=44 ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-left: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=RIGHT VALIGN=MIDDLE BGCOLOR="#FFFFFF"><FONT SIZE=1><BR></FONT></TD>
			<TD ALIGN=RIGHT VALIGN=MIDDLE BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT VALIGN=MIDDLE BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT VALIGN=MIDDLE BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT VALIGN=MIDDLE BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT VALIGN=MIDDLE BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT VALIGN=MIDDLE BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=RIGHT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-top: 5px solid #000000" COLSPAN=7 ALIGN=CENTER VALIGN=MIDDLE BGCOLOR="#FFFFFF"><B><FONT SIZE=3>Vo. Bo. Jefe Oficina Asesora de Planeación</FONT></B></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-right: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
		</TR>
		<TR>
			<TD HEIGHT=32 ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-left: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=RIGHT VALIGN=MIDDLE BGCOLOR="#FFFFFF"><FONT SIZE=1><BR></FONT></TD>
			<TD ALIGN=RIGHT VALIGN=MIDDLE BGCOLOR="#FFFFFF"><FONT SIZE=3>FECHA DE SALIDA</FONT></TD>
			<TD STYLE="border-bottom: 3px solid #333333" COLSPAN=5 ALIGN=CENTER VALIGN=MIDDLE BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=RIGHT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=RIGHT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><FONT SIZE=1><BR></FONT></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><FONT SIZE=1><BR></FONT></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><FONT SIZE=1><BR></FONT></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-right: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
		</TR>
		<TR>
			<TD HEIGHT=34 ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-left: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><FONT SIZE=1><BR></FONT></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-top: 3px solid #333333" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-top: 3px solid #333333" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-top: 3px solid #333333" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-top: 3px solid #333333" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-top: 3px solid #333333" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=CENTER BGCOLOR="#FFFFFF"><B><BR></B></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><FONT SIZE=1><BR></FONT></TD>
			
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><FONT SIZE=1><BR></FONT></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=right BGCOLOR="#FFFFFF" COLSPAN=4><FONT SIZE=1>                             ADQUISICIÓN DE BIENES Y SERVICIOS - V10</FONT></TD>
			<TD STYLE="border-right: 3px solid #000000" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
		</TR>
		<TR>
			<TD HEIGHT=26 ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-top: 5px solid #000000" ALIGN=RIGHT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-top: 5px solid #000000" ALIGN=RIGHT BGCOLOR="#FFFFFF"><FONT SIZE=1><BR></FONT></TD>
			<TD STYLE="border-top: 5px solid #000000" ALIGN=RIGHT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-top: 5px solid #000000" ALIGN=RIGHT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-top: 5px solid #000000" ALIGN=RIGHT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-top: 5px solid #000000" ALIGN=RIGHT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-top: 5px solid #000000" ALIGN=RIGHT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-top: 5px solid #000000" ALIGN=RIGHT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-top: 5px solid #000000" ALIGN=RIGHT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-top: 5px solid #000000" ALIGN=RIGHT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-top: 5px solid #333333" ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
			<TD STYLE="border-top: 5px solid #000000" COLSPAN=10 ALIGN=RIGHT><BR></TD>
			<TD ALIGN=LEFT BGCOLOR="#FFFFFF"><BR></TD>
		</TR>
	</TBODY>
</TABLE>

<!-- ************************************************************************** -->
</BODY>

</HTML>
